function y = mainFilter(x)
%MAINFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 07-Mar-2015 22:13:41

persistent Hd;

if isempty(Hd)
    
    Fstop = 10000;  % Stopband Frequency
    Fpass = 12000;  % Passband Frequency
    Astop = 60;     % Stopband Attenuation (dB)
    Apass = 1;      % Passband Ripple (dB)
    Fs    = 48000;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


